# -*- coding: utf-8 -*-
"""Lab1_Ruqaya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tDQEVtb5oXT_8NM_b6GMfQOs_kumyIs

Import libraries
"""

import numpy as np #for numerical data
import pandas as pd #for creating and working with dataframes
import matplotlib.pyplot as plt #for creating plots & charts
import seaborn as sns #for creating statistical visualizations

from sklearn.datasets import load_iris #for loading the Iris dataset

sns.set_theme(style="whitegrid") #to make plots more clear

print("Librares imported successfully")

"""1. Load the Iris dataset into a DataFrame."""

iris = load_iris() #liad dataset

#convert the numerical iris data inot pandas DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

df["species_id"] = iris.target #add numerical target for each flower

#convert numerical species id's into readable species names
df["species"]= df["species_id"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})
print("iris dataset loaded successfully")

"""2. Display the first 10 rows, shape, columns, missing values, and descriptive statistics."""

print("1st 10 rows")
display(df.head(10))

print("\nDataser shape")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nMissing val in each column:")
print(df.isnull().sum())

print("\nDescriptive statistics:")
display(df.describe())

"""3. Create at least two new derived columns."""

# Create a new derived column for petal area
# Multiply petal length by petal width
df["petal_area"] = df["petal length (cm)"] * df["petal width (cm)"]


# Create a new derived column for sepal area
# Multiply sepal length by sepal width
df["sepal_area"] = df["sepal length (cm)"] * df["sepal width (cm)"]


# Display the first 5 rows of the new derived columns
print("New derived columns:")
display(df[["petal_area", "sepal_area"]].head())


# Display the shape after adding the new columns
print("Shape after feature creation:")
print(df.shape)

"""4. Create three filtered DataFrames."""

# Create a DataFrame with flowers that have petal width greater than 1.5 cm
wide_petals = df[df["petal width (cm)"] > 1.5].copy()


# Create a DataFrame that contains only Virginica flowers
virginica_only = df[df["species"] == "virginica"].copy()


# Create a DataFrame using two conditions:
# sepal length greater than 6 cm AND petal width greater than 1.5 cm
combined_filter = df[
    (df["sepal length (cm)"] > 6) &
    (df["petal width (cm)"] > 1.5)
].copy()


# Display the shape of each filtered DataFrame
print("Wide petals:", wide_petals.shape)
print("Virginica:", virginica_only.shape)
print("Combined filter:", combined_filter.shape)

"""5. Use groupby() to compare at least two features by species."""

# Group the dataset by species and calculate the average
# petal length, petal width, and petal area for each species
species_summary = df.groupby("species")[["petal length (cm)", "petal width (cm)", "petal_area"]].mean()

# Display the comparison between the three species
print("Average features by species:")
display(species_summary)

"""6.1 Create one Matplotlib scatter"""

# Create a scatter plot to compare petal length and petal width
plt.figure(figsize=(7, 4))


# Group the flowers by species and plot each species separately
for species, group in df.groupby("species"):
    plt.scatter(
        group["petal length (cm)"],
        group["petal width (cm)"],
        label=species
    )


# Add labels and a title to the scatter plot
plt.xlabel("Petal Length (cm)")
plt.ylabel("Petal Width (cm)")
plt.title("Petal Length vs Petal Width by Species")


# Add a legend to show the three species
plt.legend(title="Species")


# Display the scatter plot
plt.show()

"""6.2 Create one Matplotlib histogram"""

# Create a histogram to show the distribution of petal width
plt.figure(figsize=(7, 4))


# Plot the distribution of petal width using 12 bins
plt.hist(df["petal width (cm)"], bins=12)


# Add labels and a title to the histogram
plt.xlabel("Petal Width (cm)")
plt.ylabel("Frequency")
plt.title("Distribution of Petal Width")


# Display the histogram
plt.show()

"""7.١ Create one Seaborn boxplot"""

# Create a boxplot to compare petal length between the three species
plt.figure(figsize=(7, 4))

sns.boxplot(
    data=df,
    x="species",
    y="petal length (cm)"
)

# Add labels and a title to the boxplot
plt.xlabel("Species")
plt.ylabel("Petal Length (cm)")
plt.title("Petal Length Distribution by Species")

# Display the boxplot
plt.show()

"""7.2 Create one Seaborn heatmap"""

# Select the four original numerical measurements
original_features = [
    "sepal length (cm)",
    "sepal width (cm)",
    "petal length (cm)",
    "petal width (cm)"
]


# Calculate the correlation between the original numerical features
correlation = df[original_features].corr()


# Create a heatmap to display the correlations
plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    vmin=-1,
    vmax=1,
    center=0
)


# Add a title to the heatmap
plt.title("Correlation Between Iris Measurements")


# Display the heatmap
plt.show()

"""8. Create or improve an OOP class with at least four methods."""

# Create a class for analyzing the Iris dataset
class IrisAnalyzer:

    # Initialize the class with the dataset
    def __init__(self, data):
        self.data = data

    # Method 1: Return the shape of the dataset
    def show_shape(self):
        return self.data.shape

    # Method 2: Count the number of flowers in each species
    def species_counts(self):
        return self.data["species"].value_counts()

    # Method 3: Calculate the average of a feature for each species
    def feature_mean_by_species(self, feature):
        return self.data.groupby("species")[feature].mean()

    # Method 4: Calculate the maximum value of a feature for each species
    def feature_max_by_species(self, feature):
        return self.data.groupby("species")[feature].max()


# Create an object from the IrisAnalyzer class
analyzer = IrisAnalyzer(df)


# Test the methods
print("Dataset shape:")
print(analyzer.show_shape())

print("\nNumber of flowers in each species:")
print(analyzer.species_counts())

print("\nAverage petal length by species:")
print(analyzer.feature_mean_by_species("petal length (cm)"))

print("\nMaximum petal length by species:")
print(analyzer.feature_max_by_species("petal length (cm)"))

"""### **9.1 The most important data pattern**

The main pattern I noticed in the Iris dataset is the difference in petal size between the three species. Setosa has the smallest petals, while Virginica has the largest. Versicolor and Virginica are more similar to each other. I could see these differences clearly in the scatter plot and boxplot.

### **9.2 How this lab prepares you for future AI topics.**

This lab helped me understand some of the steps that are needed before building a machine learning model. I learned how to explore a dataset, check for missing values, create new features, filter and group the data, and use visualizations to find patterns. Creating new columns such as petal area also gave me a simple idea of feature engineering, which can be useful later when preparing data for AI models.
"""